sudo: required
dist: trusty
language: java
jdk:
    - oraclejdk8

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-add-repository "deb http://mirror.openio.io/pub/repo/openio/sds/17.04/ubuntu/trusty ./"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libglib2.0-dev libzookeeper-mt-dev libzmq3-dev libcurl4-gnutls-dev libapreq2-dev libsqlite3-dev libattr1-dev libevent-dev apache2 apache2-dev libapache2-mod-wsgi liblzo2-dev openio-gridinit openio-asn1c libjson-c-dev flex bison curl libleveldb1 libleveldb-dev python-all-dev python-virtualenv beanstalkd liberasurecode-dev
  - virtualenv $HOME/oio && source $HOME/oio/bin/activate
  - pip install --upgrade pip setuptools virtualenv tox
  - git clone -b ${SDS_BRANCH:-master} https://github.com/open-io/oio-sds.git
  - pip install --upgrade -r oio-sds/all-requirements.txt
  - pip install --upgrade -r oio-sds/test-requirements.txt
env:
  matrix:
    - TEST_SUITE=EC
    - TEST_SUITE=EC SDS_BRANCH=4.1.x
    - TEST_SUITE=EC SDS_BRANCH=4.2.x
    - TEST_SUITE=3COPIES-11RAWX
    - TEST_SUITE=3COPIES-11RAWX SDS_BRANCH=4.1.x
    - TEST_SUITE=3COPIES-11RAWX SDS_BRANCH=4.2.x
script:
  - set -e
  - mkdir /tmp/oio
  - source $HOME/oio/bin/activate
  - cd oio-sds && cmake -DCMAKE_INSTALL_PREFIX="/tmp/oio" -DLD_LIBDIR="lib" -DCMAKE_BUILD_TYPE="Debug" -DSTACK_PROTECTOR=1 -DZK_LIBDIR="/usr/lib" -DZK_INCDIR="/usr/include/zookeeper" -DAPACHE2_LIBDIR="/usr/lib/apache2" -DAPACHE2_INCDIR="/usr/include/apache2" -DAPACHE2_MODDIR=/tmp/oio/lib/apache2/module .
  - make all install
  - python setup.py install
  - export G_DEBUG_LEVEL=D PATH="$PATH:/tmp/oio/bin" LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/tmp/oio/lib"
  - export OIO_NS="NS-${RANDOM}" OIO_ACCOUNT="ACCT-$RANDOM" OIO_USER=USER-$RANDOM OIO_PATH=PATH-$RANDOM
  - test -f etc/bootstrap-preset-${TEST_SUITE}.yml && oio-reset.sh -v -v -N $OIO_NS -f etc/bootstrap-preset-${TEST_SUITE}.yml || oio-reset.sh -v -v -N $OIO_NS -f etc/bootstrap-${TEST_SUITE}.yml
  - cd .. && ./gradlew test
  - ./gradlew assemble
after_success:
  - bash <(curl -s https://codecov.io/bash)
